.TH MRD6SH 1 "IPv6 Multicast routing daemon"
.SH NAME
mrd6 \- an IPv6 Multicast routing daemon and framework
.SH SYNOPSIS
.B mrd6sh
.I command
.SH DESCRIPTION
.B mrd6sh
allows you both to either obtain current state information from
.B mrd6
as well as to dynamically configure it.
.SH OPTIONS
Options available for the
.B mrd6
command:
.TP
.I command
The full command that will be sent to \fBmrd6\fR.
For a list of common useful commands check the included MRD6shQuickRef.txt
.SH FILES
.TP
.BI /usr/share/doc/mrd6/MRD6shQuickRef.txt
A quick reference to useful \fBmrd6\fR commands.
.SH BUGS
Report any bugs to
.BI http://fivebits.net/proj/mrd6/

